app:
  name: Jim_service
  ver: 1.0.1
  env: local
rpc:
  host: 127.0.0.1
  port: 8083
  ttl: 5
  log: log/rpc.log

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  charset: utf8mb4
  database: jim

redis:
  host: 127.0.0.1
  port: 6379
  user: ""
  password: ""
  db: 0

jaeger:
  host: 172.17.0.1
  port: 6831

jwt:
  secret: __jim__
  default_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mzk4MTUwMDQsInVpZCI6MX0.wT2xLgwOTLoJV5v-TRLFXl-f1HGyd04Vx2TPm5mzNW8

pager:
  page_size: 10

etcd:
  host:
    - 127.0.0.1:2379
  timeout: 6831
