// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"jim_service/internal/gen_model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newFeedLike(db *gorm.DB) feedLike {
	_feedLike := feedLike{}

	_feedLike.feedLikeDo.UseDB(db)
	_feedLike.feedLikeDo.UseModel(&gen_model.FeedLike{})

	tableName := _feedLike.feedLikeDo.TableName()
	_feedLike.ALL = field.NewField(tableName, "*")
	_feedLike.ID = field.NewUint64(tableName, "id")
	_feedLike.FeedID = field.NewUint64(tableName, "feed_id")
	_feedLike.UserID = field.NewUint64(tableName, "user_id")
	_feedLike.CreatedAt = field.NewTime(tableName, "created_at")
	_feedLike.UpdatedAt = field.NewTime(tableName, "updated_at")
	_feedLike.DeletedAt = field.NewField(tableName, "deleted_at")

	_feedLike.fillFieldMap()

	return _feedLike
}

type feedLike struct {
	feedLikeDo feedLikeDo

	ALL       field.Field
	ID        field.Uint64
	FeedID    field.Uint64
	UserID    field.Uint64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (f feedLike) As(alias string) *feedLike {
	f.feedLikeDo.DO = *(f.feedLikeDo.As(alias).(*gen.DO))

	f.ALL = field.NewField(alias, "*")
	f.ID = field.NewUint64(alias, "id")
	f.FeedID = field.NewUint64(alias, "feed_id")
	f.UserID = field.NewUint64(alias, "user_id")
	f.CreatedAt = field.NewTime(alias, "created_at")
	f.UpdatedAt = field.NewTime(alias, "updated_at")
	f.DeletedAt = field.NewField(alias, "deleted_at")

	f.fillFieldMap()

	return &f
}

func (f *feedLike) WithContext(ctx context.Context) *feedLikeDo { return f.feedLikeDo.WithContext(ctx) }

func (f feedLike) TableName() string { return f.feedLikeDo.TableName() }

func (f *feedLike) GetFieldByName(fieldName string) (field.Expr, bool) {
	field, ok := f.fieldMap[fieldName]
	return field, ok
}

func (f *feedLike) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 6)
	f.fieldMap["id"] = f.ID
	f.fieldMap["feed_id"] = f.FeedID
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_at"] = f.DeletedAt
}

func (f feedLike) clone(db *gorm.DB) feedLike {
	f.feedLikeDo.ReplaceDB(db)
	return f
}

type feedLikeDo struct{ gen.DO }

func (f feedLikeDo) Debug() *feedLikeDo {
	return f.withDO(f.DO.Debug())
}

func (f feedLikeDo) WithContext(ctx context.Context) *feedLikeDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f feedLikeDo) Clauses(conds ...clause.Expression) *feedLikeDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f feedLikeDo) Not(conds ...gen.Condition) *feedLikeDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f feedLikeDo) Or(conds ...gen.Condition) *feedLikeDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f feedLikeDo) Select(conds ...field.Expr) *feedLikeDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f feedLikeDo) Where(conds ...gen.Condition) *feedLikeDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f feedLikeDo) Order(conds ...field.Expr) *feedLikeDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f feedLikeDo) Distinct(cols ...field.Expr) *feedLikeDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f feedLikeDo) Omit(cols ...field.Expr) *feedLikeDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f feedLikeDo) Join(table schema.Tabler, on ...field.Expr) *feedLikeDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f feedLikeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *feedLikeDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f feedLikeDo) RightJoin(table schema.Tabler, on ...field.Expr) *feedLikeDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f feedLikeDo) Group(cols ...field.Expr) *feedLikeDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f feedLikeDo) Having(conds ...gen.Condition) *feedLikeDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f feedLikeDo) Limit(limit int) *feedLikeDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f feedLikeDo) Offset(offset int) *feedLikeDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f feedLikeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *feedLikeDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f feedLikeDo) Unscoped() *feedLikeDo {
	return f.withDO(f.DO.Unscoped())
}

func (f feedLikeDo) Create(values ...*gen_model.FeedLike) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f feedLikeDo) CreateInBatches(values []*gen_model.FeedLike, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f feedLikeDo) Save(values ...*gen_model.FeedLike) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f feedLikeDo) First() (*gen_model.FeedLike, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedLike), nil
	}
}

func (f feedLikeDo) Take() (*gen_model.FeedLike, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedLike), nil
	}
}

func (f feedLikeDo) Last() (*gen_model.FeedLike, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedLike), nil
	}
}

func (f feedLikeDo) Find() ([]*gen_model.FeedLike, error) {
	result, err := f.DO.Find()
	return result.([]*gen_model.FeedLike), err
}

func (f feedLikeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.FeedLike, err error) {
	buf := make([]*gen_model.FeedLike, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f feedLikeDo) FindInBatches(result *[]*gen_model.FeedLike, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f feedLikeDo) Attrs(attrs ...field.AssignExpr) *feedLikeDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f feedLikeDo) Assign(attrs ...field.AssignExpr) *feedLikeDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f feedLikeDo) Joins(field field.RelationField) *feedLikeDo {
	return f.withDO(f.DO.Joins(field))
}

func (f feedLikeDo) Preload(field field.RelationField) *feedLikeDo {
	return f.withDO(f.DO.Preload(field))
}

func (f feedLikeDo) FirstOrInit() (*gen_model.FeedLike, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedLike), nil
	}
}

func (f feedLikeDo) FirstOrCreate() (*gen_model.FeedLike, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedLike), nil
	}
}

func (f feedLikeDo) FindByPage(offset int, limit int) (result []*gen_model.FeedLike, count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	result, err = f.Offset(offset).Limit(limit).Find()
	return
}

func (f feedLikeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f *feedLikeDo) withDO(do gen.Dao) *feedLikeDo {
	f.DO = *do.(*gen.DO)
	return f
}
