// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"jim_service/internal/gen_model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newFeedVideo(db *gorm.DB) feedVideo {
	_feedVideo := feedVideo{}

	_feedVideo.feedVideoDo.UseDB(db)
	_feedVideo.feedVideoDo.UseModel(&gen_model.FeedVideo{})

	tableName := _feedVideo.feedVideoDo.TableName()
	_feedVideo.ALL = field.NewField(tableName, "*")
	_feedVideo.ID = field.NewUint64(tableName, "id")
	_feedVideo.FeedID = field.NewUint64(tableName, "feed_id")
	_feedVideo.VideoURL = field.NewString(tableName, "video_url")
	_feedVideo.CoverURL = field.NewString(tableName, "cover_url")
	_feedVideo.Height = field.NewInt32(tableName, "height")
	_feedVideo.Width = field.NewInt32(tableName, "width")
	_feedVideo.Duration = field.NewFloat32(tableName, "duration")
	_feedVideo.CreatedAt = field.NewTime(tableName, "created_at")
	_feedVideo.UpdatedAt = field.NewTime(tableName, "updated_at")
	_feedVideo.DeletedAt = field.NewField(tableName, "deleted_at")

	_feedVideo.fillFieldMap()

	return _feedVideo
}

type feedVideo struct {
	feedVideoDo feedVideoDo

	ALL       field.Field
	ID        field.Uint64
	FeedID    field.Uint64
	VideoURL  field.String
	CoverURL  field.String
	Height    field.Int32
	Width     field.Int32
	Duration  field.Float32
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (f feedVideo) As(alias string) *feedVideo {
	f.feedVideoDo.DO = *(f.feedVideoDo.As(alias).(*gen.DO))

	f.ALL = field.NewField(alias, "*")
	f.ID = field.NewUint64(alias, "id")
	f.FeedID = field.NewUint64(alias, "feed_id")
	f.VideoURL = field.NewString(alias, "video_url")
	f.CoverURL = field.NewString(alias, "cover_url")
	f.Height = field.NewInt32(alias, "height")
	f.Width = field.NewInt32(alias, "width")
	f.Duration = field.NewFloat32(alias, "duration")
	f.CreatedAt = field.NewTime(alias, "created_at")
	f.UpdatedAt = field.NewTime(alias, "updated_at")
	f.DeletedAt = field.NewField(alias, "deleted_at")

	f.fillFieldMap()

	return &f
}

func (f *feedVideo) WithContext(ctx context.Context) *feedVideoDo {
	return f.feedVideoDo.WithContext(ctx)
}

func (f feedVideo) TableName() string { return f.feedVideoDo.TableName() }

func (f *feedVideo) GetFieldByName(fieldName string) (field.Expr, bool) {
	field, ok := f.fieldMap[fieldName]
	return field, ok
}

func (f *feedVideo) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 10)
	f.fieldMap["id"] = f.ID
	f.fieldMap["feed_id"] = f.FeedID
	f.fieldMap["video_url"] = f.VideoURL
	f.fieldMap["cover_url"] = f.CoverURL
	f.fieldMap["height"] = f.Height
	f.fieldMap["width"] = f.Width
	f.fieldMap["duration"] = f.Duration
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_at"] = f.DeletedAt
}

func (f feedVideo) clone(db *gorm.DB) feedVideo {
	f.feedVideoDo.ReplaceDB(db)
	return f
}

type feedVideoDo struct{ gen.DO }

func (f feedVideoDo) Debug() *feedVideoDo {
	return f.withDO(f.DO.Debug())
}

func (f feedVideoDo) WithContext(ctx context.Context) *feedVideoDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f feedVideoDo) Clauses(conds ...clause.Expression) *feedVideoDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f feedVideoDo) Not(conds ...gen.Condition) *feedVideoDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f feedVideoDo) Or(conds ...gen.Condition) *feedVideoDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f feedVideoDo) Select(conds ...field.Expr) *feedVideoDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f feedVideoDo) Where(conds ...gen.Condition) *feedVideoDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f feedVideoDo) Order(conds ...field.Expr) *feedVideoDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f feedVideoDo) Distinct(cols ...field.Expr) *feedVideoDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f feedVideoDo) Omit(cols ...field.Expr) *feedVideoDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f feedVideoDo) Join(table schema.Tabler, on ...field.Expr) *feedVideoDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f feedVideoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *feedVideoDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f feedVideoDo) RightJoin(table schema.Tabler, on ...field.Expr) *feedVideoDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f feedVideoDo) Group(cols ...field.Expr) *feedVideoDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f feedVideoDo) Having(conds ...gen.Condition) *feedVideoDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f feedVideoDo) Limit(limit int) *feedVideoDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f feedVideoDo) Offset(offset int) *feedVideoDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f feedVideoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *feedVideoDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f feedVideoDo) Unscoped() *feedVideoDo {
	return f.withDO(f.DO.Unscoped())
}

func (f feedVideoDo) Create(values ...*gen_model.FeedVideo) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f feedVideoDo) CreateInBatches(values []*gen_model.FeedVideo, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f feedVideoDo) Save(values ...*gen_model.FeedVideo) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f feedVideoDo) First() (*gen_model.FeedVideo, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedVideo), nil
	}
}

func (f feedVideoDo) Take() (*gen_model.FeedVideo, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedVideo), nil
	}
}

func (f feedVideoDo) Last() (*gen_model.FeedVideo, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedVideo), nil
	}
}

func (f feedVideoDo) Find() ([]*gen_model.FeedVideo, error) {
	result, err := f.DO.Find()
	return result.([]*gen_model.FeedVideo), err
}

func (f feedVideoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.FeedVideo, err error) {
	buf := make([]*gen_model.FeedVideo, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f feedVideoDo) FindInBatches(result *[]*gen_model.FeedVideo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f feedVideoDo) Attrs(attrs ...field.AssignExpr) *feedVideoDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f feedVideoDo) Assign(attrs ...field.AssignExpr) *feedVideoDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f feedVideoDo) Joins(field field.RelationField) *feedVideoDo {
	return f.withDO(f.DO.Joins(field))
}

func (f feedVideoDo) Preload(field field.RelationField) *feedVideoDo {
	return f.withDO(f.DO.Preload(field))
}

func (f feedVideoDo) FirstOrInit() (*gen_model.FeedVideo, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedVideo), nil
	}
}

func (f feedVideoDo) FirstOrCreate() (*gen_model.FeedVideo, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.FeedVideo), nil
	}
}

func (f feedVideoDo) FindByPage(offset int, limit int) (result []*gen_model.FeedVideo, count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	result, err = f.Offset(offset).Limit(limit).Find()
	return
}

func (f feedVideoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f *feedVideoDo) withDO(do gen.Dao) *feedVideoDo {
	f.DO = *do.(*gen.DO)
	return f
}
