// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"jim_service/internal/gen_model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newGoadminMenu(db *gorm.DB) goadminMenu {
	_goadminMenu := goadminMenu{}

	_goadminMenu.goadminMenuDo.UseDB(db)
	_goadminMenu.goadminMenuDo.UseModel(&gen_model.GoadminMenu{})

	tableName := _goadminMenu.goadminMenuDo.TableName()
	_goadminMenu.ALL = field.NewField(tableName, "*")
	_goadminMenu.ID = field.NewInt32(tableName, "id")
	_goadminMenu.ParentID = field.NewInt32(tableName, "parent_id")
	_goadminMenu.Type = field.NewInt32(tableName, "type")
	_goadminMenu.Order = field.NewInt32(tableName, "order")
	_goadminMenu.Title = field.NewString(tableName, "title")
	_goadminMenu.Icon = field.NewString(tableName, "icon")
	_goadminMenu.URI = field.NewString(tableName, "uri")
	_goadminMenu.Header = field.NewString(tableName, "header")
	_goadminMenu.PluginName = field.NewString(tableName, "plugin_name")
	_goadminMenu.UUID = field.NewString(tableName, "uuid")
	_goadminMenu.CreatedAt = field.NewTime(tableName, "created_at")
	_goadminMenu.UpdatedAt = field.NewTime(tableName, "updated_at")

	_goadminMenu.fillFieldMap()

	return _goadminMenu
}

type goadminMenu struct {
	goadminMenuDo goadminMenuDo

	ALL        field.Field
	ID         field.Int32
	ParentID   field.Int32
	Type       field.Int32
	Order      field.Int32
	Title      field.String
	Icon       field.String
	URI        field.String
	Header     field.String
	PluginName field.String
	UUID       field.String
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (g goadminMenu) As(alias string) *goadminMenu {
	g.goadminMenuDo.DO = *(g.goadminMenuDo.As(alias).(*gen.DO))

	g.ALL = field.NewField(alias, "*")
	g.ID = field.NewInt32(alias, "id")
	g.ParentID = field.NewInt32(alias, "parent_id")
	g.Type = field.NewInt32(alias, "type")
	g.Order = field.NewInt32(alias, "order")
	g.Title = field.NewString(alias, "title")
	g.Icon = field.NewString(alias, "icon")
	g.URI = field.NewString(alias, "uri")
	g.Header = field.NewString(alias, "header")
	g.PluginName = field.NewString(alias, "plugin_name")
	g.UUID = field.NewString(alias, "uuid")
	g.CreatedAt = field.NewTime(alias, "created_at")
	g.UpdatedAt = field.NewTime(alias, "updated_at")

	g.fillFieldMap()

	return &g
}

func (g *goadminMenu) WithContext(ctx context.Context) *goadminMenuDo {
	return g.goadminMenuDo.WithContext(ctx)
}

func (g goadminMenu) TableName() string { return g.goadminMenuDo.TableName() }

func (g *goadminMenu) GetFieldByName(fieldName string) (field.Expr, bool) {
	field, ok := g.fieldMap[fieldName]
	return field, ok
}

func (g *goadminMenu) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 12)
	g.fieldMap["id"] = g.ID
	g.fieldMap["parent_id"] = g.ParentID
	g.fieldMap["type"] = g.Type
	g.fieldMap["order"] = g.Order
	g.fieldMap["title"] = g.Title
	g.fieldMap["icon"] = g.Icon
	g.fieldMap["uri"] = g.URI
	g.fieldMap["header"] = g.Header
	g.fieldMap["plugin_name"] = g.PluginName
	g.fieldMap["uuid"] = g.UUID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g goadminMenu) clone(db *gorm.DB) goadminMenu {
	g.goadminMenuDo.ReplaceDB(db)
	return g
}

type goadminMenuDo struct{ gen.DO }

func (g goadminMenuDo) Debug() *goadminMenuDo {
	return g.withDO(g.DO.Debug())
}

func (g goadminMenuDo) WithContext(ctx context.Context) *goadminMenuDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goadminMenuDo) Clauses(conds ...clause.Expression) *goadminMenuDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goadminMenuDo) Not(conds ...gen.Condition) *goadminMenuDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goadminMenuDo) Or(conds ...gen.Condition) *goadminMenuDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goadminMenuDo) Select(conds ...field.Expr) *goadminMenuDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goadminMenuDo) Where(conds ...gen.Condition) *goadminMenuDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goadminMenuDo) Order(conds ...field.Expr) *goadminMenuDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goadminMenuDo) Distinct(cols ...field.Expr) *goadminMenuDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goadminMenuDo) Omit(cols ...field.Expr) *goadminMenuDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goadminMenuDo) Join(table schema.Tabler, on ...field.Expr) *goadminMenuDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goadminMenuDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goadminMenuDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goadminMenuDo) RightJoin(table schema.Tabler, on ...field.Expr) *goadminMenuDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goadminMenuDo) Group(cols ...field.Expr) *goadminMenuDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goadminMenuDo) Having(conds ...gen.Condition) *goadminMenuDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goadminMenuDo) Limit(limit int) *goadminMenuDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goadminMenuDo) Offset(offset int) *goadminMenuDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goadminMenuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goadminMenuDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goadminMenuDo) Unscoped() *goadminMenuDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goadminMenuDo) Create(values ...*gen_model.GoadminMenu) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goadminMenuDo) CreateInBatches(values []*gen_model.GoadminMenu, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goadminMenuDo) Save(values ...*gen_model.GoadminMenu) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goadminMenuDo) First() (*gen_model.GoadminMenu, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminMenu), nil
	}
}

func (g goadminMenuDo) Take() (*gen_model.GoadminMenu, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminMenu), nil
	}
}

func (g goadminMenuDo) Last() (*gen_model.GoadminMenu, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminMenu), nil
	}
}

func (g goadminMenuDo) Find() ([]*gen_model.GoadminMenu, error) {
	result, err := g.DO.Find()
	return result.([]*gen_model.GoadminMenu), err
}

func (g goadminMenuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.GoadminMenu, err error) {
	buf := make([]*gen_model.GoadminMenu, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goadminMenuDo) FindInBatches(result *[]*gen_model.GoadminMenu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goadminMenuDo) Attrs(attrs ...field.AssignExpr) *goadminMenuDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goadminMenuDo) Assign(attrs ...field.AssignExpr) *goadminMenuDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goadminMenuDo) Joins(field field.RelationField) *goadminMenuDo {
	return g.withDO(g.DO.Joins(field))
}

func (g goadminMenuDo) Preload(field field.RelationField) *goadminMenuDo {
	return g.withDO(g.DO.Preload(field))
}

func (g goadminMenuDo) FirstOrInit() (*gen_model.GoadminMenu, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminMenu), nil
	}
}

func (g goadminMenuDo) FirstOrCreate() (*gen_model.GoadminMenu, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminMenu), nil
	}
}

func (g goadminMenuDo) FindByPage(offset int, limit int) (result []*gen_model.GoadminMenu, count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	result, err = g.Offset(offset).Limit(limit).Find()
	return
}

func (g goadminMenuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g *goadminMenuDo) withDO(do gen.Dao) *goadminMenuDo {
	g.DO = *do.(*gen.DO)
	return g
}
