// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_query

import (
	"context"
	"jim_service/internal/gen_model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newGoadminRolePermissions(db *gorm.DB) goadminRolePermissions {
	_goadminRolePermissions := goadminRolePermissions{}

	_goadminRolePermissions.goadminRolePermissionsDo.UseDB(db)
	_goadminRolePermissions.goadminRolePermissionsDo.UseModel(&gen_model.GoadminRolePermissions{})

	tableName := _goadminRolePermissions.goadminRolePermissionsDo.TableName()
	_goadminRolePermissions.ALL = field.NewField(tableName, "*")
	_goadminRolePermissions.RoleID = field.NewInt32(tableName, "role_id")
	_goadminRolePermissions.PermissionID = field.NewInt32(tableName, "permission_id")
	_goadminRolePermissions.CreatedAt = field.NewTime(tableName, "created_at")
	_goadminRolePermissions.UpdatedAt = field.NewTime(tableName, "updated_at")

	_goadminRolePermissions.fillFieldMap()

	return _goadminRolePermissions
}

type goadminRolePermissions struct {
	goadminRolePermissionsDo goadminRolePermissionsDo

	ALL          field.Field
	RoleID       field.Int32
	PermissionID field.Int32
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (g goadminRolePermissions) As(alias string) *goadminRolePermissions {
	g.goadminRolePermissionsDo.DO = *(g.goadminRolePermissionsDo.As(alias).(*gen.DO))

	g.ALL = field.NewField(alias, "*")
	g.RoleID = field.NewInt32(alias, "role_id")
	g.PermissionID = field.NewInt32(alias, "permission_id")
	g.CreatedAt = field.NewTime(alias, "created_at")
	g.UpdatedAt = field.NewTime(alias, "updated_at")

	g.fillFieldMap()

	return &g
}

func (g *goadminRolePermissions) WithContext(ctx context.Context) *goadminRolePermissionsDo {
	return g.goadminRolePermissionsDo.WithContext(ctx)
}

func (g goadminRolePermissions) TableName() string { return g.goadminRolePermissionsDo.TableName() }

func (g *goadminRolePermissions) GetFieldByName(fieldName string) (field.Expr, bool) {
	field, ok := g.fieldMap[fieldName]
	return field, ok
}

func (g *goadminRolePermissions) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 4)
	g.fieldMap["role_id"] = g.RoleID
	g.fieldMap["permission_id"] = g.PermissionID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g goadminRolePermissions) clone(db *gorm.DB) goadminRolePermissions {
	g.goadminRolePermissionsDo.ReplaceDB(db)
	return g
}

type goadminRolePermissionsDo struct{ gen.DO }

func (g goadminRolePermissionsDo) Debug() *goadminRolePermissionsDo {
	return g.withDO(g.DO.Debug())
}

func (g goadminRolePermissionsDo) WithContext(ctx context.Context) *goadminRolePermissionsDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goadminRolePermissionsDo) Clauses(conds ...clause.Expression) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goadminRolePermissionsDo) Not(conds ...gen.Condition) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goadminRolePermissionsDo) Or(conds ...gen.Condition) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goadminRolePermissionsDo) Select(conds ...field.Expr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goadminRolePermissionsDo) Where(conds ...gen.Condition) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goadminRolePermissionsDo) Order(conds ...field.Expr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goadminRolePermissionsDo) Distinct(cols ...field.Expr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goadminRolePermissionsDo) Omit(cols ...field.Expr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goadminRolePermissionsDo) Join(table schema.Tabler, on ...field.Expr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goadminRolePermissionsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goadminRolePermissionsDo) RightJoin(table schema.Tabler, on ...field.Expr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goadminRolePermissionsDo) Group(cols ...field.Expr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goadminRolePermissionsDo) Having(conds ...gen.Condition) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goadminRolePermissionsDo) Limit(limit int) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goadminRolePermissionsDo) Offset(offset int) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goadminRolePermissionsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goadminRolePermissionsDo) Unscoped() *goadminRolePermissionsDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goadminRolePermissionsDo) Create(values ...*gen_model.GoadminRolePermissions) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goadminRolePermissionsDo) CreateInBatches(values []*gen_model.GoadminRolePermissions, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goadminRolePermissionsDo) Save(values ...*gen_model.GoadminRolePermissions) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goadminRolePermissionsDo) First() (*gen_model.GoadminRolePermissions, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminRolePermissions), nil
	}
}

func (g goadminRolePermissionsDo) Take() (*gen_model.GoadminRolePermissions, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminRolePermissions), nil
	}
}

func (g goadminRolePermissionsDo) Last() (*gen_model.GoadminRolePermissions, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminRolePermissions), nil
	}
}

func (g goadminRolePermissionsDo) Find() ([]*gen_model.GoadminRolePermissions, error) {
	result, err := g.DO.Find()
	return result.([]*gen_model.GoadminRolePermissions), err
}

func (g goadminRolePermissionsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*gen_model.GoadminRolePermissions, err error) {
	buf := make([]*gen_model.GoadminRolePermissions, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goadminRolePermissionsDo) FindInBatches(result *[]*gen_model.GoadminRolePermissions, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goadminRolePermissionsDo) Attrs(attrs ...field.AssignExpr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goadminRolePermissionsDo) Assign(attrs ...field.AssignExpr) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goadminRolePermissionsDo) Joins(field field.RelationField) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Joins(field))
}

func (g goadminRolePermissionsDo) Preload(field field.RelationField) *goadminRolePermissionsDo {
	return g.withDO(g.DO.Preload(field))
}

func (g goadminRolePermissionsDo) FirstOrInit() (*gen_model.GoadminRolePermissions, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminRolePermissions), nil
	}
}

func (g goadminRolePermissionsDo) FirstOrCreate() (*gen_model.GoadminRolePermissions, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*gen_model.GoadminRolePermissions), nil
	}
}

func (g goadminRolePermissionsDo) FindByPage(offset int, limit int) (result []*gen_model.GoadminRolePermissions, count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	result, err = g.Offset(offset).Limit(limit).Find()
	return
}

func (g goadminRolePermissionsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g *goadminRolePermissionsDo) withDO(do gen.Dao) *goadminRolePermissionsDo {
	g.DO = *do.(*gen.DO)
	return g
}
