// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFeedVideo = "feed_video"

// FeedVideo mapped from table <feed_video>
type FeedVideo struct {
	ID        uint64         `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FeedID    uint64         `gorm:"column:feed_id;not null;default:0" json:"feed_id"`   // 所属动态id
	VideoURL  string         `gorm:"column:video_url;not null" json:"video_url"`         // 视频URL
	CoverURL  string         `gorm:"column:cover_url;not null" json:"cover_url"`         // 视频封面URL
	Height    int32          `gorm:"column:height;not null;default:0" json:"height"`     // 视频高度
	Width     int32          `gorm:"column:width;not null;default:0" json:"width"`       // 视频宽度
	Duration  float32        `gorm:"column:duration;not null;default:0" json:"duration"` // 视频时长
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName FeedVideo's table name
func (*FeedVideo) TableName() string {
	return TableNameFeedVideo
}
