// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFeed = "feed"

// Feed mapped from table <feed>
type Feed struct {
	ID           uint64         `gorm:"column:id;primaryKey;autoIncrement:false;default:0" json:"id"` // 动态 ID
	UserID       uint64         `gorm:"column:user_id;not null;default:0" json:"user_id"`             // 用户ID
	Content      string         `gorm:"column:content;not null" json:"content"`                       // 动态内容
	Type         int32          `gorm:"column:type;not null;default:0" json:"type"`                   // 动态类型
	LikeCount    int32          `gorm:"column:like_count;not null;default:0" json:"like_count"`       // 动态点赞数
	ViewCount    int32          `gorm:"column:view_count;not null;default:0" json:"view_count"`       // 动态阅读数
	CommentCount int32          `gorm:"column:comment_count;not null;default:0" json:"comment_count"` // 动态评论数
	Operator     uint64         `gorm:"column:operator;not null;default:0" json:"operator"`           // 审核人
	Remark       string         `gorm:"column:remark;not null" json:"remark"`                         // 备注
	Hot          int64          `gorm:"column:hot;not null;default:0" json:"hot"`                     // 热门排序值
	IsEnable     int32          `gorm:"column:is_enable;not null;default:1" json:"is_enable"`         // 是否启用
	ReviewStatus int32          `gorm:"column:review_status;not null;default:0" json:"review_status"` // 审核状态 0-未审核 1-已审核 2-未通过
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	FeedImage    []FeedImage    `gorm:"" json:"feed_image"`
	FeedVideo    FeedVideo      `gorm:"" json:"feed_video"`
	FeedLike     []FeedLike     `gorm:"" json:"feed_like"`
}

// TableName Feed's table name
func (*Feed) TableName() string {
	return TableNameFeed
}
