// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import "time"

const TableNameGoadminRolePermissions = "goadmin_role_permissions"

// GoadminRolePermissions mapped from table <goadmin_role_permissions>
type GoadminRolePermissions struct {
	RoleID       int32     `gorm:"column:role_id;primaryKey;autoIncrement:false" json:"role_id"`
	PermissionID int32     `gorm:"column:permission_id;primaryKey;autoIncrement:false" json:"permission_id"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GoadminRolePermissions's table name
func (*GoadminRolePermissions) TableName() string {
	return TableNameGoadminRolePermissions
}
