// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import "time"

const TableNameGoadminRoleMenu = "goadmin_role_menu"

// GoadminRoleMenu mapped from table <goadmin_role_menu>
type GoadminRoleMenu struct {
	RoleID    int32     `gorm:"column:role_id;not null" json:"role_id"`
	MenuID    int32     `gorm:"column:menu_id;not null" json:"menu_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GoadminRoleMenu's table name
func (*GoadminRoleMenu) TableName() string {
	return TableNameGoadminRoleMenu
}
