// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import "time"

const TableNameGoadminOperationLog = "goadmin_operation_log"

// GoadminOperationLog mapped from table <goadmin_operation_log>
type GoadminOperationLog struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int32     `gorm:"column:user_id;not null" json:"user_id"`
	Path      string    `gorm:"column:path;not null" json:"path"`
	Method    string    `gorm:"column:method;not null" json:"method"`
	IP        string    `gorm:"column:ip;not null" json:"ip"`
	Input     string    `gorm:"column:input;not null" json:"input"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GoadminOperationLog's table name
func (*GoadminOperationLog) TableName() string {
	return TableNameGoadminOperationLog
}
