// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import "time"

const TableNameGoadminRoleUsers = "goadmin_role_users"

// GoadminRoleUsers mapped from table <goadmin_role_users>
type GoadminRoleUsers struct {
	RoleID    int32     `gorm:"column:role_id;primaryKey;autoIncrement:false" json:"role_id"`
	UserID    int32     `gorm:"column:user_id;primaryKey;autoIncrement:false" json:"user_id"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GoadminRoleUsers's table name
func (*GoadminRoleUsers) TableName() string {
	return TableNameGoadminRoleUsers
}
