// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

import "time"

const TableNameGoadminMenu = "goadmin_menu"

// GoadminMenu mapped from table <goadmin_menu>
type GoadminMenu struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID   int32     `gorm:"column:parent_id;not null;default:0" json:"parent_id"`
	Type       int32     `gorm:"column:type;not null;default:0" json:"type"`
	Order      int32     `gorm:"column:order;not null;default:0" json:"order"`
	Title      string    `gorm:"column:title;not null" json:"title"`
	Icon       string    `gorm:"column:icon;not null" json:"icon"`
	URI        string    `gorm:"column:uri;not null" json:"uri"`
	Header     string    `gorm:"column:header" json:"header"`
	PluginName string    `gorm:"column:plugin_name;not null" json:"plugin_name"`
	UUID       string    `gorm:"column:uuid" json:"uuid"`
	CreatedAt  time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName GoadminMenu's table name
func (*GoadminMenu) TableName() string {
	return TableNameGoadminMenu
}
