// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_model

const TableNameSchemaMigrations = "schema_migrations"

// SchemaMigrations mapped from table <schema_migrations>
type SchemaMigrations struct {
	Version int64 `gorm:"column:version;primaryKey;autoIncrement:false" json:"version"`
	Dirty   bool  `gorm:"column:dirty;not null" json:"dirty"`
}

// TableName SchemaMigrations's table name
func (*SchemaMigrations) TableName() string {
	return TableNameSchemaMigrations
}
